# Generated by Django 2.0.7 on 2018-08-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSI_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarousalInfo',
            new_name='CarouselInfo',
        ),
    ]
