# Generated by Django 2.0.7 on 2018-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSI_Web', '0003_probleminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=500)),
                ('team_details', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
